### ISSUE TITLE
Admin Documents Template causing template error

### ISSUE THREAD

**Issue by moshie** [cubecart/v6#1008]
If you place a form element inside of the content textarea for a document the closing form tag closes the admin form tag.

This makes the admin submit button go outside of the admin form meaning the button does not submit the form and if you press enter to submit the form the token is outside of the form causing a CSRF error.

[Template error here](https://github.com/cubecart/v6/blob/master/admin/skins/default/templates/documents.index.php#L84)

**Comment by abrookbanks** [comment]
Reproduced.. 
![screen shot 2016-03-10 at 11 19 56](https://cloud.githubusercontent.com/assets/4520803/13668060/0d76725c-e6b2-11e5-90be-594af45f3a75.png)

**Comment by abrookbanks** [comment]
Fixed.. (BUT only if existing HTML markup is valid!)
![screen shot 2016-03-11 at 12 33 09](https://cloud.githubusercontent.com/assets/4520803/13702300/77d3047a-e785-11e5-9b08-a131cdedb739.png)

**Comment by mosh1e** [comment]
This is still not resolved the textarea closes the WYSIWYG editor?
