### ISSUE TITLE
CubeCart Security Suite Cache Button

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#2073]
When enabled, this plugin Save does not turn off the color of the Cache button. The message says the setting was saved. Go back to the Manage Extensions page and it's still colored, but click the Cache button again and the button clears. Go back and just look at the CCSS page without doing anything, and the button is colored again.

**Comment by abrookbanks** [comment]
Fixed thanks.

**Comment by Dirty-Butter** [comment]
I'm on today's commit on a couple of test sites. This is still not clearing the cache button color for me. Maybe you forgot to fix it?? I couldn't find the code you changed in the commit history, so I can't be sure I have the correct edit installed.
