### ISSUE TITLE
SagePay Form plugin not dealing with failed payments correctly

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2198]
If a customer tries and fails to complete payment on the SagePay site using the Form gateway, SagePay cancels the attempt and returns the customer to the store.

However, CubeCart shows the "order_pending" message and leaves the order at Pending status.  It should change the status to Cancelled and display the "order_failed" message instead

**Comment by russellhurst** [comment]
This issue regularly crops up on my website ropesdirect.co.uk - whilst we contact customers when we notice this has happened they all thought that the payment had been successful. Is there any chance of having this status issue corrected?

**Comment by abrookbanks** [comment]
Thanks. I fixed this with 1.0.10 https://www.cubecart.com/extensions/payment-gateways/sagepay-form

Works well.

**Comment by russellhurst** [comment]
Hello Al,

I installed the new version and have tried a couple of times making deliberate errors but the order still shows as pending and not failed. From a customer's point of view there is nothing to show that the payment failed.

Regards,
Russell

**Comment by abrookbanks** [comment]
Hmm. This works for me. Please see movie: http://static.cubecart.com/issue-2198-sagepay.mp4 

Did I miss something?

**Comment by russellhurst** [comment]
Unfortunately not for me. I try making a purchase and deliberately make mistakes in the payment – wrong card type, wrong number, and wrong expiry. With the wrong card type and number a red message appears on the sagepay screen twice but at my third wrong attempt I go straight back to the attached screenshot. Whilst it says the order is pending there is no indication that it failed. When I then log in to mysagepay to check the transaction I can see that it failed.

**Comment by abrookbanks** [comment]
I've edited your response as the email gets put here: https://github.com/cubecart/v6/issues/2198

Can you upload a screenshot on the link above? (Just drag the picture into the text area).

**Comment by abrookbanks** [comment]
Ahhhh I see. After the third attempt it bails you out to the "Pending" screen. I'm working on this..

It's strange behaviour from SagePay.

**Comment by abrookbanks** [comment]
OK so in these circumstances we have a status code "REJECTED" to work with..

**Comment by abrookbanks** [comment]
I got it covered now. It will cancel and give them a message to say the processor has rejected the transaction.

**Comment by abrookbanks** [comment]
Please try 1.0.11.

**Comment by russellhurst** [comment]
That's fantastic - many thanks for doing this.
