### ISSUE TITLE
Improve Stripe payment interface

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2342]
Can anything be done to improve the layout that is shown to customers when paying with Stripe - this is such a good company and plugin but the implementation makes it very confusing for customers

![Stripe_Payments](https://user-images.githubusercontent.com/6114431/60435344-9c27bf00-9c09-11e9-80b8-02b5023caf63.jpeg)

**Comment by abrookbanks** [comment]
The fields just need borders right? What are you suggesting?

**Comment by havenswift-hosting** [comment]
Anything that makes it look a little more professional !  In the Stripe dashboard, people can see the following 

![Stripe_Checkout](https://user-images.githubusercontent.com/6114431/60449975-1b78bb00-9c29-11e9-8f01-a846039430ff.png)

but also most other gateways have much better layouts - anything has to be an improvement, so a few boxes, a couple of images (store and maybe the cards supported etc)

**Comment by abrookbanks** [comment]
This is the default display....
![Screenshot 2019-07-01 at 16 55 53](https://user-images.githubusercontent.com/4520803/60450150-20d20780-9c21-11e9-99c4-796762912ac1.png)
Source: https://stripe.com/docs/stripe-js/elements/quickstart

**Comment by abrookbanks** [comment]
Is this better? 
![Screenshot 2019-07-01 at 16 56 49](https://user-images.githubusercontent.com/4520803/60450206-3e06d600-9c21-11e9-99c2-a6c57bffed92.png)

**Comment by abrookbanks** [comment]
I released 2.1.2 with the above changes. The text "Pay by Debit/Credit Card" is less confusing than seeing "Credit Card" twice. The fields are now also encapsulated in a darker border.

**Comment by havenswift-hosting** [comment]
Better yes, but still not immediately clear that there are three different fields there to be filled in and as I said, having a couple of small logos / images there would help as well

**Comment by abrookbanks** [comment]
It's "how it is supposed to look" now. We have to trust the Stripe UX designers a bit I think.

Let's see how this goes.

**Comment by abrookbanks** [comment]
2.2.0 now supports Strong Customer Authentication (SCA) using the payment intent API.

**Comment by havenswift-hosting** [comment]
That is excellent news - great job

Dont think much of the Stripe UX designers if that is the best they can come up with - it is however, much better than it was

**Comment by havenswift-hosting** [comment]
While you are working on it - are you able to look at some other issues ?  If a payment fails then customer is not given any details and are shown a white screen.

1) If in test mode and use live card details
2) If postcode (zipcode according to the error recorded) fails validation ( the error recorded in CubeCart error table is "[Exception] /home/caranxne/public_html/modules/gateway/Stripe/stripe-php-5.2.0/lib/ApiRequestor.php:128 - The zip code you supplied failed validation."

Maybe other causes but have seen both of these

**Comment by abrookbanks** [comment]
The error in issue 2 above suggests you are not using the 6.2.0 release which is very different. Please check as this should be fixed in the latest release.

**Comment by havenswift-hosting** [comment]
Since installing this latest release on a site approximately 50% of all payments done via Stripe are being duplicated - ie two payments are being taken at the same time.  Why some are only being taken once and some twice I have no idea but it has happened a large number of times so cannot be a coincidence and started happening immediately after the upgrade

**Comment by havenswift-hosting** [comment]
Have you had chance to look into this issue - we had to downgrade both users that had been using the latest version due to huge numbers of duplicated (sometimes 2, 3 or 4 duplicated payments for the same order !)

**Comment by abrookbanks** [comment]
I'll have a look tomorrow. If you do find a pattern I'd be grateful.

**Comment by abrookbanks** [comment]
Is it possible to look at the logs in stripe for any clues?

**Comment by abrookbanks** [comment]
I was able to reproduce this. I believe it's just a simple matter of impatient customers submitting twice. 

Code has been added to disable the "Make Payment" button showing "Please wait ..." instead.

I hope this solves this issue.

**Comment by havenswift-hosting** [comment]
OK excellent - I will try it out on the same two clients but judging by the fact that it was intermittent on both sites, that sounds like it was the cause - thanks !

**Comment by abrookbanks** [comment]
That's exactly what I thought. I was able to get the card charged twice too with the successive click.

**Comment by havenswift-hosting** [comment]
Hi Al

People love using Stripe but really dont like the very basic (although improved a little) design that is presented to customers.  Is there anything more that can be done to make it snazzier - something along the lines of my original image which one customer suggested.  I must get this 4 or 5 times a month from clients

**Comment by Prb4000** [comment]
I've just started using the Stripe plugin on our website.  The first time I saw this interface I found it quite disconcerting.  It doesn't look genuine.  I am concerned that customers, particularly new customers will be put off buying from us when they are asked to input their card details into an interface that doesn't look professional and doesn't look secure.
