### ISSUE TITLE
PayPal Commerce: Undefined Variable

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2914]
In `paypal.class.php`, line 796 and line 822, the non-existent variable `$ch` is used as an argument. Additionally, the function `curl_error()` may be used inappropriately here.

The intended instance of curl is not available because the Request class was used. I am not sure when this instance of the Request class gets destroyed. Comments suggest that once destroyed, the response to `curl_error()` is an empty string.

Additionally, there is a small difference in the logic flow between `voidOrder()` at the `if` block (line 793) and `_patchOrder()` at the `if` block (line 819) when dealing with the `trigger_error()` -- not that this matters much.

**Comment by abrookbanks** [comment]
Fixed with 1.4.8. Thanks. :)

**Comment by bhsmither** [comment]
Line 822 was not fixed.

Wondering what PayPal's actual response was:
https://forums.cubecart.com/topic/57331-paypal-commerce-cpanel-error/

**Comment by harris-organic** [comment]
Paypal Commerce.
PayPal have a lot of different integration types. Not many platforms support the new PayPal Commerce like Plesk. If Paypal standard works on a Plesk platform, why does not Paypal Commerce?
Can Paypal Commerce be made to work on Plesk?

**Comment by abrookbanks** [comment]
@harris-organic because the PayPal Standard extension doesn't use curl requests in the same way. It's a completely different solution technically.

**Comment by bhsmither** [comment]
In the `paypal.class.php`, line 856 (for version 1.6.0), the use of `curl_error($ch)` is not appropriate here.

**Comment by harris-organic** [comment]
Hi Al,

I have just spoken to my hosting company about the curl requests for PayPal commerce.

 

As you may remember my control panel is Plesk.

 

Do you know if the curl requests can be changed at the host end to allow PayPal commerce to work for me?

 

The hosting company has asked for further information so they may be able to assist.

 

kindest regards

 

Duncan Harris

**Comment by abrookbanks** [comment]
The issue you have is caused by the fact that the server doesn't have global public CA certificates installed. Any server administrator should be able to install the latest ones.

**Comment by abrookbanks** [comment]
I don't know why I reopened this as the initial issue appears resolved. @harris-organic was resolved with an OS update.

**Comment by harris-organic** [comment]
Hello Al, Could you open Gift Cards and Contact Page - SEO - 6.2.9 #2603 please or do I need to open a new issue?

 

I have just updated the request.

 

 

kindest regards

 

Duncan

**Comment by abrookbanks** [comment]
Can you open a new issue please? This looks like a feature request.
