### ISSUE TITLE
BUG - Products per category limited to 6

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#302]
This became apparent using a new custom skin in b6.

When browsing the category the "Products per page" setting is not respected. only 6 products per page are ever displayed.

After changing the "Products per page" setting the pagination tabs increase/decrease as expected but the quantity of items never changes.

var dumping the smarty variable "PRODUCTS" shows only 6 items are added to the PRODUCTS array.

When using the foundation skin a "load more" button appears at the bottom of the page, but the number of items per page is also not respected.

**Comment by abrookbanks** [comment]
Thanks for this but this is fixed already here. https://github.com/cubecart/v6/commit/202419624113ea864fd97ef823ccb8747bd38fdf

**Comment by Noodleyman** [comment]
After upgrading to the b7 release, this is still not fixed.

Total items per page now becomes 12 instead of 6 and the setting to control products per page is still not respected.

**Comment by abrookbanks** [comment]
The value in the config xml file of the skin is used. The admin setting probably needs to be removed or changed to a hidden variable for v5 skins.

**Comment by Noodleyman** [comment]
Ah!

Yes, that was the issue. I hadn't realised that would override the configured admin values. As they are default values I thought the admin area settings would override them.

I've removed those product settings from the skin config file and now it's behaving as I expected.
