### ISSUE TITLE
Warning When No Exif Data

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3550]
Minor:

In `GD->gdLoadFile()`, the command `exif_read_data()` may return false, and in that case will return:
```
Warning: File not supported
```
As an example, the Foundation image 'noimage.png' will trigger this warning.

An experiment:
```
$this->_gdImageExif = @exif_read_data($file);
```
seems to suppress the warning.

**Comment by abrookbanks** [comment]
Fixed with 88b9f4e101106d0469439dc449829c9be575a70f

**Comment by bhsmither** [comment]
I disagree.

The fix referenced above fixes the issue where the function is not available.

The issue still exists when `$file` has no exif data.
