### ISSUE TITLE
Selected Options Not Showing

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#440]
See:
https://forums.cubecart.com/topic/49477-issue-with-order-printout-missing-options/

I am really not liking lines 406-415 (Catalogue->displayProductOptions).

The `$selected_options_array` is (option_id => assign_id) -- actually, I think the assign_id alone should be sufficient, but, whatever. The logic is using the same (somewhat misnamed) variables at multiple places in ways I have not seen before.

Anyway, 'selected' in $option_list is null because `$selected[$value['assign_id']]` (at line 445) is not set. Probably because `$selected[$value['assign_id']]` is using the wrong number for the key.

Or it could be 406-415 isn't building `$selected` as thought.

**Comment by bhsmither** [comment]
The decision to be made:
- to fix the database contents and related code, or
- fix the code that uses the database contents
 We know that the assign_id is distinct everywhere. But the option_id is distinct only by current circumstance. When CubeCart eventually has the code to allow multiple option values per option group (e.g., black and tan for color), the possibility for a distinct option_id is gone.

In Catalogue->displayProductOptions(), the second argument is an array of options that have been selected by the customers for this product. For example:
The $selected_options_array is:
 (option_id)4 => (assign_id)'68'
 (option_id)1 => (assign_id)'40'

Working through the code, I conclude that when constructing `$selected`, the key and value are backwards, causing `$option_list[$value['option_id']]['selected'] to be null, because `$selected[$value['assign_id']]` is not set (undefined offset). This causes admin, Edit Order, Inventory tab to not have any option that was actually selected by the customer to be pre-selected in the selectors. Then, when submitting the form, all the options for the inventory of the order get discarded.

I suggest these code edits (only initial tests conducted):
Lines 406-415:
```
if(is_array($selected_options_array)) {
	foreach($selected_options_array as $selected_assign_id => $value) {
		if(is_array($value)) {
			foreach($value as $selected_assign_id => $value) {
				$selected[$value] = $selected_assign_id; // $selected[$selected_assign_id] = $value;
			}
		}
		$selected[$value] = $selected_assign_id; // $selected[$selected_assign_id] = $value;
	}
}
```

Line 434:
```
selected' => (isset($selected[$value['assign_id']])) ? true : false // ($selected[$value['assign_id']]) ? true : false
```
Line 445:
```
'selected' => (isset($selected[$value['assign_id']])) ? true : false // ($selected[$value['assign_id']]) ? true : false
```
Line 448:
```
if(isset($selected[$value['assign_id']])) { // if($selected[$value['assign_id']]) {
```

**Comment by webspinning** [comment]
so an item ordered with product options does not display those options in Admin etc but does appear to carry them into the automated email received by the store.

Does the fixed identified above fix it and is there a permanent resolution coming in 6.03 that we should wait for?

**Comment by tainbare** [comment]
Really need a fix for this as causing major problems with store that has a lot of persoanalised items.

**Comment by wilded1** [comment]
I have a workaround.... very dirty fix...... that will work as long as you can do without the inventory tab options; at least you can add delivery date, tracking info and change the order status and save the order whilst still keeping the products options.
See my original post on this issue on CubeCart Forums: 
https://forums.cubecart.com/topic/49477-issue-with-order-printout-missing-options/

**Comment by tainbare** [comment]
Did you try above as well?

**Comment by wilded1** [comment]
To webspinning...

the options are carried over to the orxder in admin too..
They are lost when you change the order status or add delivery info..

basically they are lost just by hitting Save in Admin Orders.

It is the fact that the Order Inventory tab does not list the options that were selected for the product ordered by default in the select list, therefore, if the order is saved the previously existing options are overwritten and nulled out.

**Comment by abrookbanks** [comment]
I;m going to take a look at this ASAP. Probably tomorrow morning...

**Comment by abrookbanks** [comment]
Ok so this is my initial finding. All seems fine aside from the option both showing red at the end instead of the one showing blue. http://static.cubecart.com/github-issue-440.mp4

Does this issue only affect orders placed in a previous last major version before upgrading to v6?

**Comment by tainbare** [comment]
You need to go one step futher and move this order to processing or save the order  by adding something then the options disapear.

**Comment by abrookbanks** [comment]
Can someone try the above fix for me? Please can you also check that your database table `CubeCart_order_inventory` has a column for `options_array`.

**Comment by abrookbanks** [comment]
> You need to go one step futher and move this order to processing or save the order by adding something then the options disapear.
@tainbare Ok cool. Thanks.. I'll do that...

**Comment by tainbare** [comment]
Do you still need someone to test above?

**Comment by abrookbanks** [comment]
.. I'm still working on this.

**Comment by abrookbanks** [comment]
All seems to be working now: http://static.cubecart.com/github-issue-440-savingoptions.mp4

**Comment by wilded1** [comment]
Superb.

**Comment by abrookbanks** [comment]
I'll try to release this as part of 6.0.3 tomorrow.

**Comment by tainbare** [comment]
Di d you release this as part of 6.03 as I upgraded and it did not seem to work.

**Comment by abrookbanks** [comment]
Yes. It works fine for me. Please place a new order and see if it works. It may not work with existing old orders.

**Comment by tainbare** [comment]
No does not seem to work.

**Comment by abrookbanks** [comment]
I just tested our demo store and it works fine. Maybe you need to send a support ticket so we can take a look. Try here: https://demo.cubecart.com/cc6

**Comment by tainbare** [comment]
Ok I have raised a ticket but I have noticed that it works on mine in dropdown selection field but it is the FREE TEXT FIELDS it is not working. This is not on any of your test products. I did try to add a free text option to one of the products to but did not seem to let me.

**Comment by abrookbanks** [comment]
This was caused by a bug in a 3rd party skin. Fixed now.

**Comment by bhsmither** [comment]
I am still getting `Notice: Undefined offset catalogue.class.php:443` and 462.

This tells me some code edits as suggested in comment-2 were not made correctly or at all.

Granted, who really cares about PHP `Notices`. But it was these notices that let me find the problem code causing the data loss more quickly than otherwise.

**Comment by abrookbanks** [comment]
I don't like PHP notices.. I hadn't made your code changes Brian. I fear adding bugs! All works fine now but it would be nice to lose the notices.. Thanks for your contribution though its not unappreciated.
