### ISSUE TITLE
Backbutton issue with ajax scroll listing of the products 

### ISSUE THREAD

**Issue by Hardwarestore** [cubecart/v6#726]
Problem: When you are in a category with lots of product and you press two times on “Get more products”(Then we are 3 steps down the page) - then visit a product by clicking on it – and then press browser "back": The page that now appear is not on step3 but on step 1 – And that is ignoring for the customer when we are talking 5 or 8 steps down. What Im looking for is that the customer return to step3 when customer leaves from step 3. I think this a problem that need attention. 

Hope for positive response.

Thanks,

**Comment by abrookbanks** [comment]
Thanks fixed with https://github.com/cubecart/v6/commit/50fbba8855d35a970fdcef9588c67e9a9b246fba

**Comment by Hardwarestore** [comment]
This did not fix the problem. It seams to return to step3 but the products in step 2 and 3 does not load?

**Comment by abrookbanks** [comment]
So pressing the more button twice is not relevant. I've reopened this.

**Comment by abrookbanks** [comment]
The above fix works for me. Please try and let me know.

**Comment by Hardwarestore** [comment]
Semperfi installed your fix on his test store:
http://cc6demo-modifications.semperfiwebservices.com/test-category.html
and it does not fix the problem.
I do not think you get the point of what I mean:
As it is now: When the user hit the back button from a product (back to the category) the user have to start over and scroll all products again to get to the place where he left.

What is needed: When the user hit the back button from a product the system need to take the user back to the same place in the category where the user left. That way the user can continue scrolling down the productlist in the category without having to stat all over everytime the user visit a product.

Does that make any sense to you?

**Comment by abrookbanks** [comment]
The fix I posted above has not been installed on that test store. 
https://github.com/cubecart/v6/commit/a9e34202d63aa2b7d0430bda5e3fe8924c4f1ed4

**Comment by abrookbanks** [comment]
I expect Daren is still in bed. I posted this new fix an hour ago and its very much bed time still in the US. Once it has been implemented the URL will get an anchor for the page number on the end (so back has somewhere to go to). Movie below:

http://static.cubecart.com/github-726.mp4

**Comment by Hardwarestore** [comment]
Great. That was what I ment! I willl have Daren checking that out. Thanks.

**Comment by abrookbanks** [comment]
Thanks for reporting the issue.

**Comment by abrookbanks** [comment]
I'm going to close this as I'm pretty confident it's a good fix. Please do let me know if there are any issues and we can reopen it.

**Comment by Hardwarestore** [comment]
Hi,
I still not think this work correct. When I test this in chrome it does not get back to the page when it was left from. I have made this video to show you:
http://www.hardware-store.dk/viewmore.mp4
(The video its Daren's shop: http://www.cubecartservices.com/test-category.html)

**Comment by Hardwarestore** [comment]
Using FireFox, clicking back takes me correctly to where I was last at in the products list.
However it does not work correctly when using either Chrome or Internet Explorer.

**Comment by lyndsiesal** [comment]
Is anyone aware of a fix for this issue?

**Comment by abrookbanks** [comment]
Duplicate of https://github.com/cubecart/v6/issues/1115

This is now resolved.
